# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

 use_frameworks!

pod 'AFNetworking'
pod 'MJRefresh',:inhibit_warnings => true
pod 'Masonry'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'SDWebImage/WebP'
pod 'CHTCollectionViewWaterfallLayout'
pod 'SDCycleScrollView',:inhibit_warnings => true
pod 'MJExtension', :inhibit_warnings => true
pod 'IQKeyboardManager'
pod 'JPush'
pod 'UMengAnalytics',:inhibit_warnings => true
pod 'GVUserDefaults'
pod 'WRNavigationBar'
pod 'ZWPlaceHolder'
pod 'WechatOpenSDK'
pod 'Bugtags'
#pod 'MatomoTracker'    #Swift版本
#pod 'PiwikTracker'     #OC埋点
pod 'NIMSDK_LITE'       #网易云信
pod 'PGDatePicker'      #日期选择器

target 'BirdDriver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  

  # Pods for BirdDriver
  
end

target 'BirdDriverBeta' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    
    
    # Pods for BirdDriverBeta
    
end
